### ISSUE TITLE
Edgetx 2.7.1 and 2.8 firmware 

### ISSUE THREAD

**Issue by pierrotm777** [olliw42/otxtelemetry#3]
Hello olliw,
What fantastic job.
I use a Radiomaster Tx16s MkII 4in1 with Edgetx 2.7.1 version.
Do you think that would be possible to build a new Edgetx version please? 
Thanks, 
Pierre

**Comment by olliw42** [comment]
hey @pierrotm777 
humans flew to moon so everything is possible, but it's not likely to happen. OTx still has several advantages over ETx for this project, especially for scripts like this one here.
Have fun, Olli
(closing since answered)
